overblog_graphql:
    definitions:
        schema:
            # To call it you need to user /graphql/default.
            # This name is used es schema parameter in App\GraphQL\Resolver\CustomResolverMap.
            default:
                query: RootQuery
                mutation: RootMutation

            # To call it you need to user /graphql/special.
            # This name is used es schema parameter in App\GraphQL\Resolver\SpecialResolverMap.
            special:
                query: SpecialQuery
        mappings:
            types:
                -
                    type: graphql
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
